spring:
  datasource:
    first-datasource:
      jdbc-url: jdbc:mysql://xxxx:3306/db?useUnicode=true&amp;characterEncoding=utf-8
      username: username
      password: password
      driver-class-name: com.mysql.jdbc.Driver
    second-datasource:
       jdbc-url: jdbc:mysql://xxxx:3306/db?useUnicode=true&amp;characterEncoding=utf-8
       username: username
       password: password
       driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


